# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: Human-Machine Intelligent Systems Lab # title of site, used in tab name and elsewhere
email: billmongan@gmail.com # default email
google: William Mongan # default name to search on Google Scholar
github: billjr99 # default GitHub user/org, without the @
#twitter: faketwitterhandle # default Twitter handle, without the @ - uncomment in _includes/footer.html
#instagram: fakeinstagramhandle # default Instagram handle, without the @ - uncomment in _includes/footer.html
#youtube: fakeyoutubechannel # default YouTube channel handle 

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: "" #/lab-website-template

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: A use-inspired research group developing and applying machine learning techniques for improved quality-of-life. # description that will show under search engine results
      background: images/network.jpg #images/test-tube.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Analytics
analytics:
  provider               :  false # false (default), "google", "google-universal", "google-tag", "custom"  
